### ISSUE TITLE
data.json doesn't comply with Amendment XX

### ISSUE THREAD

**Issue by JonseyUSDS** [cmgiven/gov-availability#1]
Currently the data point "trump" had an end date set to 'null'. To comply with the 20th Amendment to the US Constitution, this date should be changed to: "2021-01-20T12:00:00-05:00"

**Comment by PhilMiller** [comment]
That would be speculative. The current presidency could end sooner than that, by death, resignation, impeachment, uncontested 25th amendment incapacitation, etc. The only data available is that it hasn't ended *yet*

**Comment by cmgiven** [comment]
@PhilMiller is correct about what the data is intended to represent (also to do anything else would require re-writing the code). But I appreciate your studious attention to the constitutionality of this silly web thing, @JonseyUSDS.
