### ISSUE TITLE
1789-03-04 to 1789-09-29 should be counted as additional unavailability

### ISSUE THREAD

**Issue by anthonyronda** [cmgiven/gov-availability#10]
Please refer to the following link

https://www.senate.gov/artandhistory/history/anecdote/days/009week_0304.htm

To summarize:

* The new federal government began operation on March 4th

* Congress did not attain quorum until April 6th and conducted no business in the interim

* On April 6th, quorum was satisfied and Congress was able to address its first ever order of business

It is arguable that the time between March 4th and April 6th should be considered downtime. 

In addition, the first federal budget was not passed until September 29th of that year. See the following linked document (hard to read because it is written in copperplate, but the source is considered authoritative)

https://catalog.archives.gov/id/1656515

For accessibility reasons I have provided an additional source that affirms the above, though less authoritative

https://www2.gwu.edu/~ffcp/exhibit/p8/p8_8.html

It is further arguable that any period in which the federal government is in (limited) operation without a budget and not disbursing funds should be considered for downtime

**Comment by JoshuaKGoldberg** [comment]
> began operation on March 4th

Technically, it began _operating_, which I would not consider part of downtime. We could consider that more akin to "startup" time and thus not relevant to the display.

In modern terms, you might press the power button on a computer to have it start running operations, but we shouldn't start tracking downtime until the OS and relevant systems have finished booting.

**Comment by anthonyronda** [comment]
Thanks Josh! I'm receptive to that as an argument, in which case I revise to say that September 29th would become the beginning of service availability, and it's not correct to use March 4th as the service availability starting indicator

I wasn't expecting to go deep on this but it's very probable that granularity contributes to our disagreement. The service started but Congressional "productivity" and federal disbursement are essentially two different services and we should have a very clear indicator of which service we are measuring here

**Comment by cmgiven** [comment]
This is an important debate.

I don't think Congressional productivity is my intent. Nor is disbursement a particularly bright line. As I try to define my purpose, it's very easy to get twisted around, as you could argue that service availability is defined by Congress, and a lack of appropriated funds cannot ever be considered an outage as it reflects the intent of Congress. Funds are regularly not appropriated for all kinds of authorized programs, small and large, and we would not consider that to be an outage. I think the clearest line is specific to salaried Federal employees; when such employees are prevented from executing their duties, this constitutes an outage. This definition also allows for the exclusion of various lapses in appropriations that did not result in any shutdown-like symptoms.

The question then becomes what was the earliest appropriation of funds for paying employees of the government. I think HR 32 may not be the earliest appropriation of funds. That title may go to "An Act for settling the Accounts between the United States and individual States," enacted August 5. The act allows the appointment of "…a chief clerk, and such other clerks as the duties of their office may require; and that the pay of the said chief clerk be six hundred dollars per annum, and of each other clerk four hundred dollars per annum." I'm not an expert, but I think this language suggests a direct appropriation, not merely the authorization of funds to be later appropriated. Later acts setting the salaries of various officials (still preceding HR 32) specify that such salaries will be paid "Quarterly at the Treasury of the United States," which seems to strongly suggest a direct appropriation.

So perhaps the most logical start date is August 5, 1789, the date on which Congress first committed to hiring and paying the salary of a Federal employee?

Source: https://www.loc.gov/law/help/statutes-at-large/1st-congress/c1.pdf
