### ISSUE TITLE
Feature request: Display uptime average of previous administrations

### ISSUE THREAD

**Issue by lkmorlan** [cmgiven/gov-availability#11]
Besides the current administration, it would be interesting to see the uptime averages for previous administrations as well.

**Comment by aguynamedjoetoo** [comment]
https://github.com/cmgiven/gov-availability/pull/3 this PR was intended for that but the maintainer didn't want to crowd the page it seems. Regardless, should be able to run it locally and see if you're curious :D

**Comment by cmgiven** [comment]
Thanks, @Joeskyyy. :+1:
