### ISSUE TITLE
[Enhancement] Track "This Congress"

### ISSUE THREAD

**Issue by soulcutter** [cmgiven/gov-availability#2]
It may be interesting to track these statistics against the current and historical congresses also. Currently [the 116th US Congress](https://en.wikipedia.org/wiki/116th_United_States_Congress) will be the same flat zero as "this year" but it might be good insight to have in the future.

**Comment by cmgiven** [comment]
As it won't be until 2020 that this measure is meaningfully different than "this year," I think I'd prefer to keep it simpler. I'd absolutely encourage other projects that use the data to compare sessions of Congress.
