### ISSUE TITLE
Missing the second shutdown of 2018

### ISSUE THREAD

**Issue by evbarnett** [cmgiven/gov-availability#4]
Feb 8 11:00PM EST - Feb 9 9:00AM EST. 

No workers were furloughed, but it was still a shutdown technically since the government was unfunded during that period.

**Comment by PhilMiller** [comment]
This is your opportunity to make a *contribution* - submit a pull request!

**Comment by cmgiven** [comment]
I'm distinguishing between lapses in appropriations and shutdowns for the purposes of this project. Before 1980, there were numerous additional lapses in appropriations, but they didn't result in shutdown-like effects as the modern interpretation of the Anti-Deficiency Act was not in place.
