### ISSUE TITLE
[Enhancement] Add graphs

### ISSUE THREAD

**Issue by jxbadam** [cmgiven/gov-availability#5]
This information should be graphed 👍

**Comment by kallsyms** [comment]
I created https://status.us.org with the same data but using grafana to render/graph metrics.

**Comment by PhilMiller** [comment]
@kallsyms I was really hoping to see a line graph of date on the X axis, and availability (all time, per administration, respectively, to date) on the Y axis

**Comment by cmgiven** [comment]
I like @PhilMiller's thinking, that'd be cool to see. I think it's outside the scope of this project, though.

@kallsyms: I find using Grafana for this data both funny and appropriate. Kudos.
