### ISSUE TITLE
Oct 17 furlough information is incorrect

### ISSUE THREAD

**Issue by ckerr** [cmgiven/gov-availability#8]
The Oct 17 furlough happened in 1986, not 1985.

Also, according to news reports such as [this one](https://www.nytimes.com/1995/11/11/us/looking-back-previous-government-shutdowns.html), it was only for half a day and so the span of start..end should only be 4 hours, not 24.

**Comment by cmgiven** [comment]
Thanks for the correction. I've marked the half-day shutdowns as lasting from noon to midnight, so 12 hours. I'm not sure whether that's precisely correct.
